# Path to file with utxos
# Expected format: Sparrow export with 5 comma-separated columns: Date,Output (`txid:vout`),Address,Label,Value (BTC)
utxo_file = "utxos.csv"

# Network: mainnet or testnet. Default: mainnet
network = "mainnet"

[source_wallet]
# This is the wallet to spend from.
# For a regular HD wallet, fill seed with the seed words (mnemonic) and optional BIP39 passphrase (default empty - no passphrase)
seed = "word1 word2 ... wordN"
passphrase = ""

# For multisig (m-of-n), fill seed1, seed2 ... seedN, their optional passphrases and the required threshold.
# For example, if the wallet is 2-of-3, fill seed1/seed2/seed3, optional passphrase1/2/3 and set threshold = 2.
# seed1 = "word1 word2 ... wordN"
# passphrase1 = ""
# seed2 = "word1 word2 ... wordN"
# passphrase2 = ""
# seed3 = "word1 word2 ... wordN"
# passphrase3 = ""
# threshold = 2

# Max number of addresses to derive when searching for UTXO private keys
# You might need to increase this if the wallet is very deep
# Default: 2000
address_limit = 2000

[destination_wallet]
# xpub (or zpub etc) of the receiving wallet to derive receiving addresses from
xpub = ""
# Address type to derive: segwit, taproot, legacy or p2sh. Default: segwit
type = "segwit"
# If the receiving wallet already has history, you can specify the first index to use (0-based) *OR* first address to start from
# Default: 0
initial_index = 0
# initial_address = "bc1q..."

# Alternatively, set "address" to send all transactions to a single address.
# If set, xpub/type/initial_index/initial_address are ignored.
# address = "bc1q..."

[transaction]
# Fee rate to use in sat/vb
fee_rate = 1

# Random fee increase in basis points to make it harder to determine the transactions come from the same wallet
# Ex: if fee_rate is 5.15 and fee_variation is 20, fees will vary between 5.15 and 5.35
# Default: 0
fee_variation = 50
